// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnimationType } from "./AnimationType";

export type AnimationConfig = { element_id: string, animation_type: AnimationType, custom_delay: number | null, stroke_color: string | null, inherit_children: boolean, };
