// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CarouselItem } from "./CarouselItem";

export type CarouselOptions = { id: string, orientation: string | null, show_navigation: boolean | null, items: Array<CarouselItem>, };
