// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DialogContent } from "./DialogContent";

export type DialogOptions = { id: string, title: string | null, description: string | null, content: DialogContent | null, attributes: { [key in string]?: string } | null, };
