// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DialogButton } from "./DialogButton";
import type { RawHtml } from "./RawHtml";

export type DialogOptions = { id: string, title: RawHtml | null, description: string | null, content: RawHtml | null, has_footer: boolean | null, footer_buttons: Array<DialogButton> | null, };
