// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DialogOptions = { id: string, title: string | null, description: string | null, content: string | null, attributes: { [key in string]?: string } | null, };
