// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GlowFilterProps } from "./GlowFilterProps";

/**
 * A visitor that injects GlowFilter components into SVG elements
 */
export type FilterVisitor = { glow_filters: { [key in string]?: GlowFilterProps }, 
/**
 * Track whether we're inside an SVG element
 */
inside_svg: boolean, 
/**
 * Store filters to be added to current SVG
 */
pending_filters: Array<GlowFilterProps>, };
