// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnimationConfig } from "./AnimationConfig";

export type FramerMotionVisitor = { animations: { [key in string]?: AnimationConfig }, custom_counter: number, current_parent_id: string | null, current_parent_config: AnimationConfig | null, inside_svg: boolean, };
