// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GlowFilterProps = { id: string, color: string, intensity: number | null, animated: boolean | null, duration: number | null, delay: number | null, easing: 'linear' | 'easeIn' | 'easeOut' | 'easeInOut' | 'circIn' | 'circOut' | 'backOut', glowLayers: number | null, maxIntensity: number | null, pulsing: boolean | null, interactive: boolean | null, onHover: string | null, };
