// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HoverCardOptions = { id: string, trigger_id: string | null, title: string | null, description: string | null, content: string | null, open_delay: number | null, close_delay: number | null, };
