// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RoutingLibrary } from "./RoutingLibrary";

export type LinkOptions = { id: string, href: string, target: string | null, rel: string | null, as_button: boolean, variant: string | null, size: string | null, routing_library: RoutingLibrary | null, class_name: string | null, replace: boolean, prefetch: boolean, };
