// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A wrapper around raw HTML content that can be parsed into JSX elements.
 * This is useful for handling HTML content that needs to be processed as JSX.
 */
export type RawHtml = string;
