// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ToastOptions = { id: string, title: string | null, description: string | null, variant: string | null, action_label: string | null, action: string | null, duration: number | null, };
