// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TooltipOptions = { id: string, trigger_id: string | null, content: string, side: string | null, align: string | null, delay_duration: number | null, skip_delay_duration: number | null, };
