/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.34.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject28Meta {
    /// A map of temporary ids in the request to the real ids of the newly created objects
    #[serde(rename = "tempIdToRealId")]
    pub temp_id_to_real_id: std::collections::HashMap<String, String>,
}

impl InlineObject28Meta {
    pub fn new(temp_id_to_real_id: std::collections::HashMap<String, String>) -> InlineObject28Meta {
        InlineObject28Meta {
            temp_id_to_real_id,
        }
    }
}

