/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.34.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject5 {
    /// The team's name.
    #[serde(rename = "name")]
    pub name: String,
    /// An array of projects.
    #[serde(rename = "projects")]
    pub projects: Vec<models::Project>,
}

impl InlineObject5 {
    pub fn new(name: String, projects: Vec<models::Project>) -> InlineObject5 {
        InlineObject5 {
            name,
            projects,
        }
    }
}

