/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.34.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject10 {
    /// An array of reactions.
    #[serde(rename = "reactions")]
    pub reactions: Vec<models::Reaction>,
    #[serde(rename = "pagination")]
    pub pagination: Box<models::ResponsePagination>,
}

impl InlineObject10 {
    pub fn new(reactions: Vec<models::Reaction>, pagination: models::ResponsePagination) -> InlineObject10 {
        InlineObject10 {
            reactions,
            pagination: Box::new(pagination),
        }
    }
}

