/*
 * Figma API
 *
 * This is the OpenAPI specification for the [Figma REST API](https://www.figma.com/developers/api).  Note: we are releasing the OpenAPI specification as a beta given the large surface area and complexity of the REST API. If you notice any inaccuracies with the specification, please [file an issue](https://github.com/figma/rest-api-spec/issues).
 *
 * The version of the OpenAPI document: 0.34.0
 * Contact: support@figma.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InlineObject30 {
    /// An array of links created.
    #[serde(rename = "links_created")]
    pub links_created: Vec<models::DevResource>,
    /// An array of errors.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::InlineObject30ErrorsInner>>,
}

impl InlineObject30 {
    pub fn new(links_created: Vec<models::DevResource>) -> InlineObject30 {
        InlineObject30 {
            links_created,
            errors: None,
        }
    }
}

