// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccordionItem } from "./AccordionItem";

export type AccordionOptions = { id: string, type_: string | null, collapsible: boolean | null, items: Array<AccordionItem>, };
