// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccordionOptions } from "./AccordionOptions";
import type { ButtonOptions } from "./ButtonOptions";
import type { CarouselOptions } from "./CarouselOptions";
import type { DialogOptions } from "./DialogOptions";
import type { DrawerOptions } from "./DrawerOptions";
import type { HoverCardOptions } from "./HoverCardOptions";
import type { LinkOptions } from "./LinkOptions";
import type { PopoverOptions } from "./PopoverOptions";
import type { SheetOptions } from "./SheetOptions";
import type { TooltipOptions } from "./TooltipOptions";

export type ComponentWrapper = { "type": "Dialog" } & DialogOptions | { "type": "HoverCard" } & HoverCardOptions | { "type": "Popover" } & PopoverOptions | { "type": "Sheet" } & SheetOptions | { "type": "Tooltip" } & TooltipOptions | { "type": "Link" } & LinkOptions | { "type": "Drawer" } & DrawerOptions | { "type": "Button" } & ButtonOptions | { "type": "Accordion" } & AccordionOptions | { "type": "Carousel" } & CarouselOptions;
