// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DialogContent = { "type": "RawHtml", "props": string } | { "type": "TsxImport", "props": { import_path: string, import_name: string | null, } } | { "type": "Uri", "props": string };
