// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnimationConfig } from "./AnimationConfig";
import type { Callback } from "./Callback";
import type { ComponentWrapper } from "./ComponentWrapper";
import type { JsonValue } from "./serde_json/JsonValue";
import {
  Transition,
  TargetAndTransition,
  VariantLabels,
  Variants,
  AnimationControls,
  
} from "../../figma-app/node_modules/motion/react";

type Initial = TargetAndTransition | VariantLabels | boolean;
type Exit = TargetAndTransition | VariantLabels;
type Animate = AnimationControls | TargetAndTransition | VariantLabels | boolean;

export type FigmaConversion = {
  source_file: string;
  callbacks: { [key in string]?: Array<Callback> };
  component_wrappers: { [key in string]?: ComponentWrapper };
  action_imports: { [key in string]?: Array<string> };
  animations: { [key in string]?: AnimationConfig<Initial, Animate, Exit, Variants, Transition> };
};
