// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnimationConfig } from "./AnimationConfig";
import type { Callback } from "./Callback";
import type { ComponentWrapper } from "./ComponentWrapper";
import type { GlowFilterProps } from "./GlowFilterProps";
import type { JsonValue } from "./serde_json/JsonValue";

export type FigmaConversion = { source_file: string, callbacks: { [key in string]?: Array<Callback> }, component_wrappers: { [key in string]?: ComponentWrapper }, action_imports: { [key in string]?: Array<string> }, animations: { [key in string]?: AnimationConfig<JsonValue, JsonValue, JsonValue, JsonValue, JsonValue> }, filters: { [key in string]?: GlowFilterProps }, };
