// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TypeExpression } from "./TypeExpression";

export type FunctionParameter = { name: string, type_expr: TypeExpression, optional: boolean, rest: boolean, };
