// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FunctionParameter } from "./FunctionParameter";
import type { TypeExpression } from "./TypeExpression";

export type HandlerFunction = { name: string, parameters: Array<FunctionParameter>, return_type: TypeExpression, code: string | null, };
