// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PopoverOptions = { id: string, trigger_id: string | null, title: string | null, description: string | null, content: string | null, alignment: string | null, };
