// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SheetButton } from "./SheetButton";

export type SheetOptions = { id: string, trigger_id: string | null, title: string | null, description: string | null, side: string | null, content: string | null, has_footer: boolean | null, footer_buttons: Array<SheetButton> | null, };
