// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ShowToastOptions } from "./ShowToastOptions";

export type Action = { "type": "Toast" } & ShowToastOptions;
