// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DialogButton = { label: string, variant: string | null, action: string | null, };
