// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DialogButton } from "./DialogButton";

export type DialogOptions = { id: string, title: string | null, description: string | null, content: string | null, has_footer: boolean | null, footer_buttons: Array<DialogButton> | null, };
