// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppRouterEntry } from "./AppRouterEntry";
import type { AssetFolderKind } from "./AssetFolderKind";

export type Directory<T> = { path_segment: string, relative_path: string, children: Array<AppRouterEntry<T>>, } & ({ "directory_kind": "AssetFolder", asset_kind: AssetFolderKind, } | { "directory_kind": "StaticRoute" } | { "directory_kind": "DynamicRoute" } | { "directory_kind": "CatchAllRoute" } | { "directory_kind": "PrivateRoute" } | { "directory_kind": "RouteGroup" } | { "directory_kind": "DynamicRouteWithParams" } | { "directory_kind": "DynamicRouteWithOptionalParams" } | { "directory_kind": "DynamicRouteWithOptionalParamsAndCatchAll" } | { "directory_kind": "NamedSlot" } | { "directory_kind": "InterceptSameLevel" } | { "directory_kind": "InterceptOneLevelAbove" } | { "directory_kind": "InterceptTwoLevelsAbove" } | { "directory_kind": "InterceptFromRoot" });
