// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Event = "Click" | "Hover" | "Focus" | "Change" | "Submit" | "HoverStart" | "HoverEnd" | "Drag" | "DragStart" | "DragEnd" | "AnimationStart" | "AnimationComplete" | "ViewportEnter" | "ViewportLeave" | "Tap" | "TapStart" | "TapCancel" | "Pan" | "PanStart" | "PanEnd" | "MouseEnter" | "MouseLeave" | "KeyDown" | "KeyUp" | "TouchStart" | "TouchEnd" | "TouchMove" | "TouchCancel" | "Wheel";
