// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type File<T> = { path_segment: string, relative_path: string, data: T, } & ({ "file_kind": "Layout" } | { "file_kind": "Page" } | { "file_kind": "Loading" } | { "file_kind": "NotFound" } | { "file_kind": "Error" } | { "file_kind": "GlobalError" } | { "file_kind": "Route" } | { "file_kind": "Template" } | { "file_kind": "Default" } | { "file_kind": "Other" });
