// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Callback } from "./Callback";

/**
 * A visitor that adds event handlers to JSX elements and transforms JSX structure
 */
export type InjectCallbacksVisitor = { callbacks: { [key in string]?: Array<Callback> }, };
