// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LinkOptions = { id: string, href: string, target: string | null, rel: string | null, as_button: boolean | null, variant: string | null, size: string | null, };
