// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SonnerOptions = { id: string, position: string | null, theme: string | null, expand: boolean | null, close_button: boolean | null, offset: string | null, };
