[package]
name = "etch_core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
walkdir = { workspace = true }
thiserror = { workspace = true }
etch_tsx = { workspace = true }