cargo-features = ["edition2024"]

[package]
name = "etch_core"
version = "0.1.0"
edition.workspace = true


[dependencies]
serde = { workspace = true }
walkdir = { workspace = true }
thiserror = { workspace = true }
etch_tsx = { workspace = true }